spring.application.name=littlebookstore
spring.profiles.active=${APP_PROFILE:prod}

spring.jpa.open-in-view=false

spring.datasource.url=jdbc:postgresql://localhost:5432/LivrariaCapela
spring.datasource.username=root
spring.datasource.password=root

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ------------Configuração para armazenamento de imagens na nuvem---------------------------------- #
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}


